export const Labels = {
  firstName: 'Ad',
  lastName: 'Soyad',
  fatherName: 'Ata adı',
  birthDate: 'Təvəllüd',
  gender: 'Cins',
  city: 'Şəhər',
  fin: 'FIN Kod',
  phoneNumber: 'Mobil nömrə',
  newPhoneNumber: 'Yeni mobil nömrə',
  enterPhoneNumber: 'Mobil nömrə daxil edin',
  phoneNumberisNotValid: 'Mobil nömrə düzgün daxil edilməyib',
  profession: 'Peşə',
  experience: 'Təcrübə',
  specifications: 'Spesifikasiyalar',
  expectedSalary: 'Istənilən əmək haqqı',
  search: 'Axtar',
  select: 'Seçin',
  created: 'Yaranma tarixi',
  description: 'Təsviri',
  jobDescription: 'İşin təsviri',
  required: 'Tələb olunur',
  maximum200Symbols: 'Maksimum 200 simvol',
  paymentRange: 'Ödəniş aralığı',
  onAgreedPrice: 'Razılaşma yolu ilə',
  amountOfPeople: 'İşçi sayı',
  age: 'Yaş',
  between: 'Arasında',
  with: 'ilə',
  optional: 'Qeyri-məcburi',
  workExperience: 'İş təcrübəsi',
  apply: 'Müraciət et',
  createAnnouncement: 'Elan yarat',
  createOrder: 'Sifariş yarat',
  myOrders: 'Əmək Birjası',
  myAnnouncements: 'Əmək Yarmarkası',
  announcements: 'Elanlar',
  resultFound: 'nəticə tapıldı',
  selected: 'seçilib',
  setAddress: 'Ünvanı təyin edin',
  next: 'Növbəti',
  specification: 'Spesifikasiya',
  people: 'nəfər',
  call: 'Zəng',
  submit: 'Təsdiq et',
  cancelOrder: 'Sifarişi ləğv et',
  accept: 'Qəbul et',
  decline: 'İmtina et',
  noItem: 'Məlumat tapılmadı',
  loading: 'Yüklənir',
  endOfPage: 'Səhifənin sonu',
  announcementType: 'Elanın tipi',
  seeAll: 'Hamısını gör',
  noMatter: 'Fərqi yoxdur',
  seasonal: 'Mövsümi',
  longTerm: 'Uzun müddətli',
  announcementDeadline: 'Son müraciət tarixi',
  deleteAnnouncement: 'Elanı sil',
  status: 'Status',
  showResult: 'Nəticəni göstər',
  cancelSearch: 'Nəticəni ləğv et',
  cancel: 'Ləğv et',
  save: 'Yadda saxla',
  agency: 'Təşkilat',
  address: 'Ünvan',
  finishOrder: 'Sifarişi bitir',
  yes: 'Bəli',
  no: 'Xeyr',
  finish: 'Bitir',
  'User already exists': 'İstifadəçi artıq mövcüddur',
  vote: 'səs',
  enterProfession: 'Peşə daxil edin',
  enterSpecification: 'Spesifikasiya daxil edin',
  enterExperience: 'Təzrübə daxil edin',
  enterSalary: 'Əmək haqqı daxil edin',
  exit: 'Çıxış'
};
